# Generated by Django 4.1.2 on 2023-01-18 19:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("catalog", "0002_alter_category_slug"),
        ("catalog", "0002_product_slug"),
    ]

    operations = []
