# Generated by Django 4.1.2 on 2023-03-25 16:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("catalog", "0004_product_top_seller"),
    ]

    operations = [
        migrations.CreateModel(
            name="ProductSize",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("size", models.CharField(max_length=5, verbose_name="Розмір")),
            ],
            options={
                "verbose_name": "Розмір товару",
                "verbose_name_plural": "Розміри товарів",
                "ordering": ["size"],
            },
        ),
        migrations.AlterModelOptions(
            name="productimage",
            options={
                "verbose_name": "Фото товару",
                "verbose_name_plural": "Фото товарів",
            },
        ),
        migrations.AddField(
            model_name="product",
            name="size",
            field=models.ManyToManyField(
                blank=True, null=True, to="catalog.productsize"
            ),
        ),
    ]
