# Generated by Django 4.1.2 on 2023-03-26 16:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("catalog", "0006_alter_productsize_options_alter_product_size"),
    ]

    operations = [
        migrations.AlterField(
            model_name="product",
            name="size",
            field=models.ManyToManyField(
                blank=True, to="catalog.productsize", verbose_name="Розмір"
            ),
        ),
    ]
