# Generated by Django 4.1.2 on 2023-04-10 18:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("catalog", "0008_product_selected"),
    ]

    operations = [
        migrations.AddField(
            model_name="productimage",
            name="is_main",
            field=models.BooleanField(default=False, verbose_name="Головна"),
        ),
    ]
