# Generated by Django 4.1.2 on 2023-01-24 12:53

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ("cart", "0004_alter_cartitem_product"),
    ]

    operations = [
        migrations.RemoveField(model_name="cart", name="created_at",),
        migrations.AddField(
            model_name="cart",
            name="created",
            field=models.DateTimeField(
                auto_now_add=True, db_index=True, default=django.utils.timezone.now
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="cart",
            name="updated",
            field=models.DateTimeField(auto_now=True, db_index=True, null=True),
        ),
    ]
