# Generated by Django 4.1.2 on 2023-01-24 13:00

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ("cart", "0005_remove_cart_created_at_cart_created_cart_updated"),
    ]

    operations = [
        migrations.AddField(
            model_name="cartitem",
            name="created",
            field=models.DateTimeField(
                auto_now_add=True, db_index=True, default=django.utils.timezone.now
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="cartitem",
            name="updated",
            field=models.DateTimeField(auto_now=True, db_index=True, null=True),
        ),
    ]
