# Generated by Django 4.1.2 on 2023-02-02 15:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("catalog", "0004_product_top_seller"),
        ("cart", "0006_cartitem_created_cartitem_updated"),
    ]

    operations = [
        migrations.AlterField(
            model_name="cartitem",
            name="product",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="catalog.product",
            ),
        ),
    ]
