# Generated by Django 4.1.2 on 2023-03-11 10:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cart", "0007_alter_cartitem_product"),
    ]

    operations = [
        migrations.AlterField(
            model_name="cart",
            name="status",
            field=models.CharField(
                choices=[("Open", "Open"), ("Closed", "Closed")], max_length=50
            ),
        ),
    ]
