# Generated by Django 4.1.2 on 2023-03-11 11:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cart", "0008_alter_cart_status"),
    ]

    operations = [
        migrations.AlterField(
            model_name="cart",
            name="status",
            field=models.CharField(
                choices=[("Open", "Open"), ("Closed", "Closed")],
                default="Open",
                max_length=10,
            ),
        ),
    ]
