# Generated by Django 4.1.2 on 2023-03-21 16:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cart", "0011_alter_cart_user"),
    ]

    operations = [
        migrations.AlterField(
            model_name="cart",
            name="token",
            field=models.CharField(blank=True, max_length=16, null=True, unique=True),
        ),
    ]
