# Generated by Django 4.1.2 on 2023-02-21 18:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("order", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="order",
            name="region",
            field=models.CharField(blank=True, max_length=250),
        ),
        migrations.AddField(
            model_name="order",
            name="town",
            field=models.CharField(blank=True, max_length=250),
        ),
    ]
