# Generated by Django 4.1.2 on 2023-03-02 12:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("order", "0002_order_region_order_town"),
    ]

    operations = [
        migrations.AlterField(
            model_name="order", name="address", field=models.CharField(max_length=250),
        ),
        migrations.AlterField(
            model_name="order", name="region", field=models.CharField(max_length=250),
        ),
        migrations.AlterField(
            model_name="order", name="town", field=models.CharField(max_length=250),
        ),
    ]
