# Generated by Django 4.1.2 on 2023-03-24 14:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("order", "0003_alter_order_address_alter_order_region_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="order",
            name="comment",
            field=models.TextField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name="order",
            name="order_number",
            field=models.CharField(default="955 404 769", max_length=11),
        ),
        migrations.AddField(
            model_name="order",
            name="status",
            field=models.CharField(
                choices=[
                    ("Виконано", "Done"),
                    ("Виконується", "In Progress"),
                    ("Скасовано", "Cancelled"),
                ],
                default="Виконується",
                max_length=11,
            ),
        ),
    ]
