# Generated by Django 4.1.2 on 2023-03-24 15:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("order", "0004_order_comment_order_order_number_order_status"),
    ]

    operations = [
        migrations.AlterField(
            model_name="order",
            name="order_number",
            field=models.CharField(default="815 806 429", max_length=11, unique=True),
        ),
    ]
