# Generated by Django 4.1.2 on 2023-03-27 19:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("order", "0006_alter_order_order_number"),
    ]

    operations = [
        migrations.AlterField(
            model_name="order",
            name="email",
            field=models.EmailField(
                blank=True,
                error_messages="Введіть email-адресу коректно",
                max_length=254,
            ),
        ),
    ]
