# Generated by Django 4.1.2 on 2023-03-27 19:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("order", "0008_alter_order_email"),
    ]

    operations = [
        migrations.AlterField(
            model_name="order",
            name="email",
            field=models.EmailField(
                blank=True,
                error_messages={"invalid": "Введіть коректний email"},
                max_length=254,
            ),
        ),
    ]
