# Generated by Django 4.1.2 on 2023-03-27 19:15

from django.db import migrations, models
import order.models


class Migration(migrations.Migration):

    dependencies = [
        ("order", "0009_alter_order_email"),
    ]

    operations = [
        migrations.AlterField(
            model_name="order",
            name="email",
            field=models.EmailField(
                blank=True, max_length=254, validators=[order.models.email_validator]
            ),
        ),
    ]
